version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile for FastAPI
    ports:
      - "8000:8000" # Port mapping (host:container)
    extra_hosts:
      - "host.docker.internal:host-gateway" # Required for Docker
    depends_on:
      - mongodb # Depends on the MongoDB service
    environment:
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: prod
      MONGO_DB_USERNAME: dev
      MONGO_DB_PASSWORD: dev
      SECRET_KEY: secret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1030
      REFRESH_TOKEN_EXPIRE_DAYS: 30
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017" # Port mapping (host:container)
    volumes:
      - mongodb_data:/data/db # Volume for MongoDB data persistence
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
